scratchdir: "/vast/palmer/scratch/dunn/sc2962/20230918_kmer/"

sample:
  KM5633:
    reads:
      - /vast/palmer/home.mccleary/sc2962/palmer_scratch/physalia_novaseq_2023/Sample_KM5633_150_043/
  KM5632:
    reads:
      - /vast/palmer/home.mccleary/sc2962/palmer_scratch/physalia_novaseq_2023/Sample_KM5632_138_055/ 
  YPM-IZ-110556:
    reads:
      - /vast/palmer/home.mccleary/sc2962/palmer_scratch/physalia_novaseq_2023/Sample_110556_153_040/
  YPM-IZ-110269:
    reads:
      - /vast/palmer/home.mccleary/sc2962/palmer_scratch/physalia_novaseq_2023/Sample_110469_108_085/
  YPM-IZ-110469:
    reads:
      - /vast/palmer/home.mccleary/sc2962/palmer_scratch/physalia_novaseq_2023/Sample_110269_243_334/
  YPM-IZ-GoCJUN6:
    reads:
      - /vast/palmer/home.mccleary/sc2962/palmer_scratch/physalia_novaseq_2023/Sample_GoCJUN6_195_382/
  OA-190531-1:
    reads:
      - /vast/palmer/home.mccleary/sc2962/palmer_scratch/physalia_novaseq_2023/Sample_190531_FD09253810/
  Bluebottle-OA:
    reads:      
       - /vast/palmer/scratch/dunn/sc2962/physalia_genome_assemblies/2023_physalia_pacfic_genome/GON10891/GON10891A1/
  YPM-IZ-104465:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_NA22_176_017/
  YPM-IZ-104464:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_NA24_164_029/
  YPM-IZ-110251:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_YPM110251_114_079/
  YPM-IZ-110254:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_YPM110254_102_091/
  YPM-IZ-106943:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_Bermuda_67_162_031/
  YPM-IZ-106954:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_Bermuda_94_150_043/
  YPM-IZ-106923:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_6_Japan_126_067/
  YPM-IZ-106920:
    reads: 
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_3_Japan_138_055/
         #  TX2017-38-8CELLS:
         #    reads:
         #      - /vast/palmer/scratch/dunn/sc2962/2023_physalia_tx_data/hifi
  WAMZ88480:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_Z88480_170_023/
  YPM-IZ-110738:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_110738_124_069/
  YPM-IZ-110828:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_110828_159_034/
  YPM-IZ-110842:
    reads:
       - /vast/palmer/scratch/dunn/sc2962/physalia_novaseq_2023/Sample_110842_147_046/