---
title: "_Physalia_ global population genomics: Fig. 1"
format:
  html:
    embed-resources: true
theme: cosmo
---

Samuel H. Church

Initiated: March, 2023

```{r init}
#| include: false

library(gridExtra)
library(ggplot2)
#library(RcppCNPy)
library(dplyr)
library(knitr)
library(kableExtra)
library(tidyr)
library(ggtree)
library(ggrepel)
library(maps)
library(ape)
library(phytools)
library(viridis)

library(sf)
library(rnaturalearth)
library(rnaturalearthdata)

theme_set(theme_classic())
```

```{r setup}
#| echo: false
metadata <- read.delim("../data/metadata.tsv",header=T,stringsAsFactors=F) %>% filter(status %in% c("sequenced","sequenced elsewhere"))

sample_info <- read.delim("../data/sample_ids.tsv",header=T,stringsAsFactors=F) %>%
  mutate(year = gsub(".*/(.*)","\\1",date_collected), month = as.numeric(gsub("(.*)/.*/.*","\\1",date_collected))) %>% 
  separate(lat_long,into=c("lat","long"),sep=", ")
locations <- sample_info %>% pull(location) %>% unique()

colors <- c("#E78AC3","#00008B","#800000","#DAA520","#006400","#A6D854","#DC143C","#FC8D62","#452a00","#8DA0CB","#66C2A5","#B3B3B3")
names(colors) <- c("Central Pacific","E Indian","Gulf of California","Gulf of Mexico","NE Atlantic","NW Atlantic","NW Pacific","SE Pacific","SW Atlantic","SW Pacific","W Indian")

ocean_levels <- c("Gulf of Mexico","NW Atlantic","NE Atlantic","SW Atlantic","W Indian","E Indian","SW Pacific","NW Pacific","Central Pacific","Gulf of California","SE Pacific")
sample_info$ocean <- factor(sample_info$ocean,levels=ocean_levels)

inat <- read.delim("../data/inaturalist_scores/inat_lat_long.tsv",header=T,sep="\t") %>% filter(!is.na(longitude) & !is.na(latitude))
``` 

```{r map}
#| echo: false
#| fig-width: 12
#| fig-height: 6

# set up the globe and projection
LeftBound = -90
world <- ne_countries(scale = "medium", returnclass = "sf") %>% st_set_crs(4326)
robinson = paste("+proj=robin +lon_0=",LeftBound," +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs",sep="")
world2 = world %>% st_break_antimeridian(lon_0 = LeftBound) %>% st_transform(crs = robinson)

si <- sample_info %>% mutate(lat = as.numeric(lat), lon = as.numeric(long)) %>% 
  mutate(lat = round(lat,0), long = round(lon,0)) %>% group_by(lat,lon,ocean) %>% tally()

transpoint = st_as_sf(si,coords=c("lon","lat"),crs=4326)
dtran = st_transform(transpoint,robinson)

transinat <- st_as_sf(inat,coords=c("longitude","latitude"),crs=4326)
itran <- st_transform(transinat,robinson)

g1 <- ggplot(data=world2) + geom_sf(fill = "light gray", colour = NA) +
  geom_point(data=itran,aes(geometry=geometry), size = 1, color = "orangered3", alpha=0.7,pch=16 ,stat="sf_coordinates") + 
  geom_point(data=dtran,aes(geometry=geometry, size = n), color = "royalblue2", alpha=0.7,pch=16 ,stat="sf_coordinates") + 
  #theme(legend.position = "none") +
  ggtitle(paste0(sum(si$n)," total samples")) + 
  scale_size(range = c(3,8),breaks=c(1,round(max(si$n)/2,0),15,max(si$n))) + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

g2 <-  ggplot(data=world2) + geom_sf(fill = "light gray", colour = NA) +
  geom_point(data=dtran,aes(geometry=geometry, size = n, color = ocean), alpha=0.7,pch=16 ,stat="sf_coordinates") +
  #theme(legend.position = "none") +
  ggtitle(paste0(sum(si$n)," total samples")) + 
  scale_color_manual(values = colors) + 
  scale_size(range = c(2,8),breaks=c(1,round(max(si$n)/2,0),15,max(si$n))) + 
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

png(file="../figures/panels/map_sampling.png",height=1400,width=2400,res=300)
print(g1)
dev.off()

png(file="../figures/panels/map_sampling_regions.png",height=1400,width=2400,res=300)
print(g2)
dev.off()
```

```{r cov}
dir <- "../results/strict/"
name <- "strict"
bam_list <- paste0(dir,"strict_bam.filelist")

PC_info <- data.frame(ID = read.table(bam_list,head=F) %>% 
  apply(.,1,function(x){gsub(".*sorted/(.*)_pic.bam","\\1",x)})) %>% 
  left_join(.,sample_info,by="ID")

cov <- as.matrix(read.table(paste0(dir,name,".cov")))
e <- eigen(cov)
exp_var <- paste0(round(e$values / sum(e$values) *100,1),"%")

n_vectors <- ncol(e$vectors)
e_vectors <- e$vectors[,1:n_vectors]
colnames(e_vectors) <- paste0("PC",seq(1:n_vectors))
PC_info <- bind_cols(PC_info,e_vectors)

eigen_plot <- ggplot(data.frame(eigenvalues = e$values, 
                      k = seq(1:length(e$values))),
                aes(y = eigenvalues, x = k)) + 
  geom_vline(xintercept = 5, linetype="dashed") + 
  geom_point() + 
  scale_x_continuous(limits = c(0,30),breaks=c(0,1,2,3,4,5,10,20,30))

png(paste0("../figures/panels/cov_",name,".png"),width=1200,height=800,res=300)
print(eigen_plot)
dev.off()
```

```{r PCA}
g4 <- ggplot(PC_info,aes(y=PC2,x=-1*PC1,label=ID)) +
  geom_vline(xintercept=0, linetype="dotted", color="dark gray") +
  geom_hline(yintercept=0, linetype="dotted", color="dark gray") +
  geom_point(size=2.5,alpha=0.5,pch=16,color="royalblue2") + 
  ylab(paste0("PC2 : ",exp_var[2])) + 
  xlab(paste0("PC1 : ",exp_var[1])) + 
  theme(legend.position="none") 

g6 <- ggplot(PC_info,aes(y=PC3,x=-1*PC1,label=ID)) +
  geom_vline(xintercept=0, linetype="dotted", color="dark gray") +
  geom_hline(yintercept=0, linetype="dotted", color="dark gray") +
  geom_point(size=2.5,alpha=0.5,pch=16,color="royalblue2") + 
  ylab(paste0("PC3 : ",exp_var[3])) + 
  xlab(paste0("PC1 : ",exp_var[1])) + 
  theme(legend.position="none") 
  
g7 <- ggplot(PC_info,aes(y=PC1,x=PC2,label=ID,color=ocean)) + #color=lubridate::mdy(date_collected))) + 
  geom_vline(xintercept=0, linetype="dotted", color="dark gray") +
  geom_hline(yintercept=0, linetype="dotted", color="dark gray") +
  geom_point(size=2.5,alpha=0.75,pch=16) + 
  ylab(paste0("pcangsd PC1 : ",exp_var[1])) + 
  xlab(paste0("pcangsd PC2 : ",exp_var[2])) + 
  theme(legend.position="none") +
  scale_color_manual(values = colors)

g8 <- ggplot(PC_info,aes(y=PC1,x=PC3,label=ID,color=ocean)) + #color=lubridate::mdy(date_collected))) + 
  geom_vline(xintercept=0, linetype="dotted", color="dark gray") +
  geom_hline(yintercept=0, linetype="dotted", color="dark gray") +
  geom_point(size=2.5,alpha=0.75,pch=16) + 
  ylab(paste0("pcangsd PC1 : ",exp_var[1])) + 
  xlab(paste0("pcangsd PC3 : ",exp_var[3])) + 
  theme(legend.position="none") +
  scale_color_manual(values = colors)

pdf(file=paste0("../figures/panels/",name,"_PC1.pdf"),width=3,height=3,useDingbats=F)
print(g4)
dev.off()

pdf(file=paste0("../figures/panels/",name,"_PC3.pdf"),width=3,height=3,useDingbats=F)
print(g6)
dev.off()

pdf(file=paste0("../figures/panels/",name,"_PC1_ocean.pdf"),width=5,height=2.5,useDingbats=F)
print(g7)
dev.off()

pdf(file=paste0("../figures/panels/",name,"_PC3_ocean.pdf"),width=5,height=2.5,useDingbats=F)
print(g8)
dev.off()
```
