scratchdir: "/gpfs/gibbs/pi/dunn/sc2962/20230901_Physalia_PopGen/"
analysisdir: "B2_results/"
regiondir: "/gpfs/gibbs/pi/dunn/sc2962/20230901_Physalia_PopGen/ANGSD/region_files/"

genome: "/gpfs/gibbs/pi/dunn/sc2962/Physalia_TX2017-38_HiFi_primary/Physalia_TX2017-38_HiFi_primary.fa"
all_nonrepeat_regions: "/gpfs/gibbs/pi/dunn/sc2962/20230901_Physalia_PopGen/regions.tsv"

min_qual: 40
min_depth: 2
max_depth: 99
sample_size: 50000

sample:
 - YPM-IZ-111163
 - YPM-IZ-110877
 - YPM-IZ-110878
 - YPM-IZ-110931
 - YPM-IZ-110943
 - OA-190531-1
 - OA-Bluebottle
 - WAMZ97902
 - WAMZ97907
 - WAMZ97908
 - WAMZ97910
 - WAMZ97911
 - WAMZ97914
 - WAMZ97916
 - WAMZ97917
 - WAMZ97921
 - WAMZ97923
 - YPM-IZ-104460
 - YPM-IZ-104461
 - YPM-IZ-104464
 - YPM-IZ-104465
 - YPM-IZ-106919
 - YPM-IZ-106920
 - YPM-IZ-106923
 - YPM-IZ-110264
 - YPM-IZ-110268
 - YPM-IZ-110269
 - YPM-IZ-110276
 - YPM-IZ-110277
 - YPM-IZ-110278
 - YPM-IZ-110460
 - YPM-IZ-110471
 - YPM-IZ-110473
 - YPM-IZ-110474
 - YPM-IZ-110480
 - YPM-IZ-110515
 - YPM-IZ-110520
 - YPM-IZ-110526
 - YPM-IZ-110566
 - YPM-IZ-110569
 - YPM-IZ-110600
 - YPM-IZ-110602
 - YPM-IZ-110605
 - YPM-IZ-110612
 - YPM-IZ-110613
 - YPM-IZ-110616
 - YPM-IZ-110777
 - YPM-IZ-110780
 - YPM-IZ-110785
 - YPM-IZ-110786
 - YPM-IZ-110830
 - YPM-IZ-110881
 - YPM-IZ-110882
 - YPM-IZ-110883
 - YPM-IZ-110906
 - YPM-IZ-110907
 - YPM-IZ-110925
 - YPM-IZ-110926
 - YPM-IZ-110930
 - YPM-IZ-110933
 - YPM-IZ-110937
 - YPM-IZ-110938
 - YPM-IZ-111006
 - YPM-IZ-111007
 - YPM-IZ-111008
 - YPM-IZ-111009
  
regions:
 - aaaa
 - aabn
 - aada
 - aaen
 - aaga
 - aahn
 - aaja
 - aakn
 - aama
 - aann
 - aapa
 - aaqn
 - aasa
 - aatn
 - aava
 - aawn
 - aaya
 - aazn
 - abba
 - abcn
 - abea
 - abfn
 - abha
 - abin
 - abka
 - abln
 - aaab
 - aabo
 - aadb
 - aaeo
 - aagb
 - aaho
 - aajb
 - aako
 - aamb
 - aano
 - aapb
 - aaqo
 - aasb
 - aato
 - aavb
 - aawo
 - aayb
 - aazo
 - abbb
 - abco
 - abeb
 - abfo
 - abhb
 - abio
 - abkb
 - ablo
 - aaac
 - aabp
 - aadc
 - aaep
 - aagc
 - aahp
 - aajc
 - aakp
 - aamc
 - aanp
 - aapc
 - aaqp
 - aasc
 - aatp
 - aavc
 - aawp
 - aayc
 - aazp
 - abbc
 - abcp
 - abec
 - abfp
 - abhc
 - abip
 - abkc
 - ablp
 - aaad
 - aabq
 - aadd
 - aaeq
 - aagd
 - aahq
 - aajd
 - aakq
 - aamd
 - aanq
 - aapd
 - aaqq
 - aasd
 - aatq
 - aavd
 - aawq
 - aayd
 - aazq
 - abbd
 - abcq
 - abed
 - abfq
 - abhd
 - abiq
 - abkd
 - ablq
 - aaae
 - aabr
 - aade
 - aaer
 - aage
 - aahr
 - aaje
 - aakr
 - aame
 - aanr
 - aape
 - aaqr
 - aase
 - aatr
 - aave
 - aawr
 - aaye
 - aazr
 - abbe
 - abcr
 - abee
 - abfr
 - abhe
 - abir
 - abke
 - ablr
 - aaaf
 - aabs
 - aadf
 - aaes
 - aagf
 - aahs
 - aajf
 - aaks
 - aamf
 - aans
 - aapf
 - aaqs
 - aasf
 - aats
 - aavf
 - aaws
 - aayf
 - aazs
 - abbf
 - abcs
 - abef
 - abfs
 - abhf
 - abis
 - abkf
 - abls
 - aaag
 - aabt
 - aadg
 - aaet
 - aagg
 - aaht
 - aajg
 - aakt
 - aamg
 - aant
 - aapg
 - aaqt
 - aasg
 - aatt
 - aavg
 - aawt
 - aayg
 - aazt
 - abbg
 - abct
 - abeg
 - abft
 - abhg
 - abit
 - abkg
 - ablt
 - aaah
 - aabu
 - aadh
 - aaeu
 - aagh
 - aahu
 - aajh
 - aaku
 - aamh
 - aanu
 - aaph
 - aaqu
 - aash
 - aatu
 - aavh
 - aawu
 - aayh
 - aazu
 - abbh
 - abcu
 - abeh
 - abfu
 - abhh
 - abiu
 - abkh
 - ablu
 - aaai
 - aabv
 - aadi
 - aaev
 - aagi
 - aahv
 - aaji
 - aakv
 - aami
 - aanv
 - aapi
 - aaqv
 - aasi
 - aatv
 - aavi
 - aawv
 - aayi
 - aazv
 - abbi
 - abcv
 - abei
 - abfv
 - abhi
 - abiv
 - abki
 - ablv
 - aaaj
 - aabw
 - aadj
 - aaew
 - aagj
 - aahw
 - aajj
 - aakw
 - aamj
 - aanw
 - aapj
 - aaqw
 - aasj
 - aatw
 - aavj
 - aaww
 - aayj
 - aazw
 - abbj
 - abcw
 - abej
 - abfw
 - abhj
 - abiw
 - abkj
 - ablw
 - aaak
 - aabx
 - aadk
 - aaex
 - aagk
 - aahx
 - aajk
 - aakx
 - aamk
 - aanx
 - aapk
 - aaqx
 - aask
 - aatx
 - aavk
 - aawx
 - aayk
 - aazx
 - abbk
 - abcx
 - abek
 - abfx
 - abhk
 - abix
 - abkk
 - ablx
 - aaal
 - aaby
 - aadl
 - aaey
 - aagl
 - aahy
 - aajl
 - aaky
 - aaml
 - aany
 - aapl
 - aaqy
 - aasl
 - aaty
 - aavl
 - aawy
 - aayl
 - aazy
 - abbl
 - abcy
 - abel
 - abfy
 - abhl
 - abiy
 - abkl
 - ably
 - aaam
 - aabz
 - aadm
 - aaez
 - aagm
 - aahz
 - aajm
 - aakz
 - aamm
 - aanz
 - aapm
 - aaqz
 - aasm
 - aatz
 - aavm
 - aawz
 - aaym
 - aazz
 - abbm
 - abcz
 - abem
 - abfz
 - abhm
 - abiz
 - abkm
 - ablz
 - aaan
 - aaca
 - aadn
 - aafa
 - aagn
 - aaia
 - aajn
 - aala
 - aamn
 - aaoa
 - aapn
 - aara
 - aasn
 - aaua
 - aavn
 - aaxa
 - aayn
 - abaa
 - abbn
 - abda
 - aben
 - abga
 - abhn
 - abja
 - abkn
 - abma
 - aaao
 - aacb
 - aado
 - aafb
 - aago
 - aaib
 - aajo
 - aalb
 - aamo
 - aaob
 - aapo
 - aarb
 - aaso
 - aaub
 - aavo
 - aaxb
 - aayo
 - abab
 - abbo
 - abdb
 - abeo
 - abgb
 - abho
 - abjb
 - abko
 - abmb
 - aaap
 - aacc
 - aadp
 - aafc
 - aagp
 - aaic
 - aajp
 - aalc
 - aamp
 - aaoc
 - aapp
 - aarc
 - aasp
 - aauc
 - aavp
 - aaxc
 - aayp
 - abac
 - abbp
 - abdc
 - abep
 - abgc
 - abhp
 - abjc
 - abkp
 - abmc
 - aaaq
 - aacd
 - aadq
 - aafd
 - aagq
 - aaid
 - aajq
 - aald
 - aamq
 - aaod
 - aapq
 - aard
 - aasq
 - aaud
 - aavq
 - aaxd
 - aayq
 - abad
 - abbq
 - abdd
 - abeq
 - abgd
 - abhq
 - abjd
 - abkq
 - abmd
 - aaar
 - aace
 - aadr
 - aafe
 - aagr
 - aaie
 - aajr
 - aale
 - aamr
 - aaoe
 - aapr
 - aare
 - aasr
 - aaue
 - aavr
 - aaxe
 - aayr
 - abae
 - abbr
 - abde
 - aber
 - abge
 - abhr
 - abje
 - abkr
 - abme
 - aaas
 - aacf
 - aads
 - aaff
 - aags
 - aaif
 - aajs
 - aalf
 - aams
 - aaof
 - aaps
 - aarf
 - aass
 - aauf
 - aavs
 - aaxf
 - aays
 - abaf
 - abbs
 - abdf
 - abes
 - abgf
 - abhs
 - abjf
 - abks
 - abmf
 - aaat
 - aacg
 - aadt
 - aafg
 - aagt
 - aaig
 - aajt
 - aalg
 - aamt
 - aaog
 - aapt
 - aarg
 - aast
 - aaug
 - aavt
 - aaxg
 - aayt
 - abag
 - abbt
 - abdg
 - abet
 - abgg
 - abht
 - abjg
 - abkt
 - abmg
 - aaau
 - aach
 - aadu
 - aafh
 - aagu
 - aaih
 - aaju
 - aalh
 - aamu
 - aaoh
 - aapu
 - aarh
 - aasu
 - aauh
 - aavu
 - aaxh
 - aayu
 - abah
 - abbu
 - abdh
 - abeu
 - abgh
 - abhu
 - abjh
 - abku
 - abmh
 - aaav
 - aaci
 - aadv
 - aafi
 - aagv
 - aaii
 - aajv
 - aali
 - aamv
 - aaoi
 - aapv
 - aari
 - aasv
 - aaui
 - aavv
 - aaxi
 - aayv
 - abai
 - abbv
 - abdi
 - abev
 - abgi
 - abhv
 - abji
 - abkv
 - abmi
 - aaaw
 - aacj
 - aadw
 - aafj
 - aagw
 - aaij
 - aajw
 - aalj
 - aamw
 - aaoj
 - aapw
 - aarj
 - aasw
 - aauj
 - aavw
 - aaxj
 - aayw
 - abaj
 - abbw
 - abdj
 - abew
 - abgj
 - abhw
 - abjj
 - abkw
 - abmj
 - aaax
 - aack
 - aadx
 - aafk
 - aagx
 - aaik
 - aajx
 - aalk
 - aamx
 - aaok
 - aapx
 - aark
 - aasx
 - aauk
 - aavx
 - aaxk
 - aayx
 - abak
 - abbx
 - abdk
 - abex
 - abgk
 - abhx
 - abjk
 - abkx
 - abmk
 - aaay
 - aacl
 - aady
 - aafl
 - aagy
 - aail
 - aajy
 - aall
 - aamy
 - aaol
 - aapy
 - aarl
 - aasy
 - aaul
 - aavy
 - aaxl
 - aayy
 - abal
 - abby
 - abdl
 - abey
 - abgl
 - abhy
 - abjl
 - abky
 - abml
 - aaaz
 - aacm
 - aadz
 - aafm
 - aagz
 - aaim
 - aajz
 - aalm
 - aamz
 - aaom
 - aapz
 - aarm
 - aasz
 - aaum
 - aavz
 - aaxm
 - aayz
 - abam
 - abbz
 - abdm
 - abez
 - abgm
 - abhz
 - abjm
 - abkz
 - aaba
 - aacn
 - aaea
 - aafn
 - aaha
 - aain
 - aaka
 - aaln
 - aana
 - aaon
 - aaqa
 - aarn
 - aata
 - aaun
 - aawa
 - aaxn
 - aaza
 - aban
 - abca
 - abdn
 - abfa
 - abgn
 - abia
 - abjn
 - abla
 - aabb
 - aaco
 - aaeb
 - aafo
 - aahb
 - aaio
 - aakb
 - aalo
 - aanb
 - aaoo
 - aaqb
 - aaro
 - aatb
 - aauo
 - aawb
 - aaxo
 - aazb
 - abao
 - abcb
 - abdo
 - abfb
 - abgo
 - abib
 - abjo
 - ablb
 - aabc
 - aacp
 - aaec
 - aafp
 - aahc
 - aaip
 - aakc
 - aalp
 - aanc
 - aaop
 - aaqc
 - aarp
 - aatc
 - aaup
 - aawc
 - aaxp
 - aazc
 - abap
 - abcc
 - abdp
 - abfc
 - abgp
 - abic
 - abjp
 - ablc
 - aabd
 - aacq
 - aaed
 - aafq
 - aahd
 - aaiq
 - aakd
 - aalq
 - aand
 - aaoq
 - aaqd
 - aarq
 - aatd
 - aauq
 - aawd
 - aaxq
 - aazd
 - abaq
 - abcd
 - abdq
 - abfd
 - abgq
 - abid
 - abjq
 - abld
 - aabe
 - aacr
 - aaee
 - aafr
 - aahe
 - aair
 - aake
 - aalr
 - aane
 - aaor
 - aaqe
 - aarr
 - aate
 - aaur
 - aawe
 - aaxr
 - aaze
 - abar
 - abce
 - abdr
 - abfe
 - abgr
 - abie
 - abjr
 - able
 - aabf
 - aacs
 - aaef
 - aafs
 - aahf
 - aais
 - aakf
 - aals
 - aanf
 - aaos
 - aaqf
 - aars
 - aatf
 - aaus
 - aawf
 - aaxs
 - aazf
 - abas
 - abcf
 - abds
 - abff
 - abgs
 - abif
 - abjs
 - ablf
 - aabg
 - aact
 - aaeg
 - aaft
 - aahg
 - aait
 - aakg
 - aalt
 - aang
 - aaot
 - aaqg
 - aart
 - aatg
 - aaut
 - aawg
 - aaxt
 - aazg
 - abat
 - abcg
 - abdt
 - abfg
 - abgt
 - abig
 - abjt
 - ablg
 - aabh
 - aacu
 - aaeh
 - aafu
 - aahh
 - aaiu
 - aakh
 - aalu
 - aanh
 - aaou
 - aaqh
 - aaru
 - aath
 - aauu
 - aawh
 - aaxu
 - aazh
 - abau
 - abch
 - abdu
 - abfh
 - abgu
 - abih
 - abju
 - ablh
 - aabi
 - aacv
 - aaei
 - aafv
 - aahi
 - aaiv
 - aaki
 - aalv
 - aani
 - aaov
 - aaqi
 - aarv
 - aati
 - aauv
 - aawi
 - aaxv
 - aazi
 - abav
 - abci
 - abdv
 - abfi
 - abgv
 - abii
 - abjv
 - abli
 - aabj
 - aacw
 - aaej
 - aafw
 - aahj
 - aaiw
 - aakj
 - aalw
 - aanj
 - aaow
 - aaqj
 - aarw
 - aatj
 - aauw
 - aawj
 - aaxw
 - aazj
 - abaw
 - abcj
 - abdw
 - abfj
 - abgw
 - abij
 - abjw
 - ablj
 - aabk
 - aacx
 - aaek
 - aafx
 - aahk
 - aaix
 - aakk
 - aalx
 - aank
 - aaox
 - aaqk
 - aarx
 - aatk
 - aaux
 - aawk
 - aaxx
 - aazk
 - abax
 - abck
 - abdx
 - abfk
 - abgx
 - abik
 - abjx
 - ablk
 - aabl
 - aacy
 - aael
 - aafy
 - aahl
 - aaiy
 - aakl
 - aaly
 - aanl
 - aaoy
 - aaql
 - aary
 - aatl
 - aauy
 - aawl
 - aaxy
 - aazl
 - abay
 - abcl
 - abdy
 - abfl
 - abgy
 - abil
 - abjy
 - abll
 - aabm
 - aacz
 - aaem
 - aafz
 - aahm
 - aaiz
 - aakm
 - aalz
 - aanm
 - aaoz
 - aaqm
 - aarz
 - aatm
 - aauz
 - aawm
 - aaxz
 - aazm
 - abaz
 - abcm
 - abdz
 - abfm
 - abgz
 - abim
 - abjz
 - ablm
